import type { Metadata, Viewport } from "next";
import { Archivo, IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Sprite } from "@/components/site/sprite";
import { Curtain } from "@/components/site/curtain";
import { Motion } from "@/components/site/motion";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { WhatsAppButton } from "@/components/whatsapp-button";
import { OrganizationJsonLd } from "@/components/seo/json-ld";
import { company } from "@/data/company";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  axes: ["wdth"],
  display: "swap",
});

const plexSans = IBM_Plex_Sans({
  variable: "--font-plex-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(`https://${company.domain}`),
  title: {
    default: `${company.name} — ${company.tagline}`,
    template: `%s · ${company.name}`,
  },
  description: company.description,
  applicationName: company.name,
  authors: [{ name: company.name }],
  publisher: company.name,
  keywords: [
    "Bilal Pharmaceuticals",
    "animal health",
    "animal health importer Pakistan",
    "veterinary vaccines",
    "feed additives",
    "water sanitizers",
    "biosecurity",
    "animal health distributor Islamabad",
  ],
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    url: "/",
    locale: "en_US",
    title: `${company.name} — ${company.tagline}`,
    description: company.description,
    siteName: company.name,
    // Branded 1200×630 share card is generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: `${company.name} — ${company.tagline}`,
    description: company.description,
  },
  // Favicons are file-based (white background): app/favicon.ico, app/icon.png,
  // app/apple-icon.png — generated from the transparent B/P mark (public/logo-bi.png).
  formatDetection: { telephone: false },
  // TODO: paste the Google Search Console verification code once the domain is
  // verified, then uncomment. (Bing: add `other: { "msvalidate.01": "..." }`.)
  // verification: { google: "GSC_VERIFICATION_CODE" },
};

export const viewport: Viewport = {
  themeColor: "#be1e7a", // brand magenta (--primary in globals.css)
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${archivo.variable} ${plexSans.variable} ${plexMono.variable}`}
    >
      <body>
        <OrganizationJsonLd />
        <Providers>
          <Sprite />
          <Curtain />
          <div className="progress" id="prog" />
          <SiteHeader />
          <main id="pages">{children}</main>
          <SiteFooter />
          <WhatsAppButton />
          <Motion />
        </Providers>
      </body>
    </html>
  );
}
